Blog/accounts/urls.py
"""Define URL patterns for accounts"""
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    #Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    #Registration page
    path('register/', views.register, name = 'register'),
]

Blog/blog/urls.py
"""Defines URL patterns for blog"""

from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    #Home page
    path('', views.index, name = 'index'),
    path('all_blogs/', views.blogs, name = 'blogs'),
    #So when we go to the all_blogs page we calls the blogs function in the view.py file and pass the argument 'blog' to it as the request

    #Detail page for a single topic
    path('all_blogs/<int:blog_id>/', views.blog, name = 'blog'),
    #So this was failig at first because I was calling the blog function in views.blog... and I was returning the blog and blog_posts key-value
    #That dictionary was then getting passed to the blog.html file
    #Which tries to loop through blog_posts. Where I failed at first was I had erroneously named blog_posts as blog_post. Missing the s
    #The for loop therefore could not find a blog_posts key. And assumed there was no data to be found

    #Page for adding a new topic
    path('new_blog/', views.new_blog, name = 'new_blog'),
    
    #Page for adding a new entry
    path('new_blog_post/<int:blog_id>/', views.new_blog_post, name = 'new_blog_post'),

    #Page for editing an entry
    path('edit_blog_post/<int:blog_post_id>/', views.edit_blog_post, name = 'edit_blog_post'),
]

Blog/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
    #Looking at the blog folder and the urls file in it
]

Blog/accounts/models.py
from django.db import models

# Create your models here.

Blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Blog(models.Model):
    """A topic the user is posting about"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text


#Creating an Entry Model that can be nested under a Topic
class Blog_Post(models.Model):
    """Something specific enter about a topic"""
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.text) > 50: 
            return f"{self.text[:50]}..."
        
        #The ellipsis (...) is to remind the UI that we're not presenting the entire entry. Well. It shows anyway even if you have less than 50 characters so woops oh well.

        else:
            return f"{self.text}"
        

Blog/blog/forms.py
from django import forms
from .models import Blog, Blog_Post

class Blog_Form(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['text']
        labels = {'text': ''}
        #We're importing the Topic model defined in the models file, using it as a template, and telling this that the only field we want from Topics is the text field. Not the date_added.
        #Then we want this text key in the label dictionary to not have a value paired with it

class Blog_Post_Form(forms.ModelForm):
    class Meta:
        model = Blog_Post
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        #Here we are telling Django to expand the number of columns in the text box to 80. Instead of the default 40

Blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        #Display blank registration form.
        form  = UserCreationForm()
    else:
        #Process completed form
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            #Log the user in and then redirect to the home page
            login(request, new_user)
            return redirect('blog:index')
        
    #Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

Blog/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, Blog_Post
from .forms import Blog_Form, Blog_Post_Form

# Create your views here.
def index(request):
    """The home page for Blog."""
    return render(request, 'blog/index.html')
    #Looking at the blog folder and the index.html file in it


def blogs(request):
    """Show all blogs"""
    blogs = Blog.objects.order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blog/blogs.html', context)


def blog(request, blog_id):
    """Show a single blog and all of its entries"""
    blog = Blog.objects.get(id = blog_id)
    blog_posts = blog.blog_post_set.order_by('-date_added')
    #THE LOWERCASE ENTRY IS REFERENCING THE BLOG POST CLASS IN THE MODELS.PY FILE.
    #IF YOU WANT TO USE FOREIGN_KEYS PROPERLY AND GRAB MANY ITEMS ASSOCIATED TO A SINGLE PIZZA OR TOPIC FOR EXAMPLE
    #YOU WOULD GO (name goes here).(LOWERCASE CLASS NAME)_set.
    context = {'blog': blog, 'blog_posts': blog_posts}
    return render(request, 'blog/blog.html', context)


@login_required
def new_blog(request):
    """Add a new blog"""
    
    #Make this match the functions in the urls.py folder within the blog folder
    if request.method != 'POST':
        #No data submitted; create a blank form
        #When the User first hits or enters this page their browser is sending a GET request
        #So this is triggered when first hitting the page. If the user submits a form then that is a POST request
        form = Blog_Form()

    else:
        #POST data submitted; process data
        form = Blog_Form(data = request.POST)
        if form.is_valid():
            #The save method writes this to the DB
            new_blog = form.save(commit = False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blog:blogs')
            #I think this redirect is saying use the the topics function above which calls a new HTML page to redirect you to.


    #Display a blank or invalid form
    context = {'form': form}
    return render(request, 'blog/new_blog.html', context)


@login_required
def new_blog_post(request, blog_id):
    """Add a new entry for a particular topic"""
    blog = Blog.objects.get(id=blog_id)
    
    #Make sure blog belongs to current user
    check_blog_owner(request, blog)
    
    #Grabbing an individual blog
    if request.method != 'POST':
        #No data submitted; create a blank form
        form = Blog_Post_Form()

    else:
        #POST data submitted; process data.
        form = Blog_Post_Form(data = request.POST)
        if form.is_valid():
            new_blog_post = form.save(commit = False)
            new_blog_post.blog = blog
            new_blog_post.save()
            return redirect('blog:blog', blog_id = blog_id)
            #Telling it to call the topic function above

    #Display a blank or invalid form
    context = {'blog': blog, 'form': form}
    return render(request, 'blog/new_blog_post.html', context)


@login_required
def edit_blog_post(request, blog_post_id):
    """Edit an existing entry"""
    blog_post = Blog_Post.objects.get(id = blog_post_id)
    blog = blog_post.blog

    #Make sure blog belongs to current user
    check_blog_owner(request, blog)

    if request.method != 'POST':
        #Initial request; pre-fill form with the current entry.
        form = Blog_Post_Form(instance = blog_post)
    else:
        #POST data submitted; process data
        form = Blog_Post_Form(instance = blog_post, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:blog', blog_id = blog.id)
            #Telling it to call the blog function above

    context = {'blog_post': blog_post, 'blog': blog, 'form': form}
    return render(request, 'blog/edit_blog_post.html', context) 



def check_blog_owner(request, blog):
    #Make sure the topic belongs to the current user.
    if blog.owner != request.user:
        raise Http404

Blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blogly</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blog:index' %}">Index</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:blogs' %}">Blogs</a>
                    </li>
                </ul> <!--End of links on left side of navbar-->

                <!--Account related links-->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                    <li class="" nav-item>
                        <span class="navbar-text me-2"> Hello, {{user.username}}.</span>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                    </li>
                    {% endif %}

                </ul> <!--End of account-releated links-->

                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method='post'>
                    {% csrf_token %}
                    <button name='submit' class="btn btn-outline-secondary btn-sm">Log out</button>
                </form>
                {% endif %}

            </div> <!--Closes collapsible parts of navbar-->
        </div> <!--Closes navbar's container-->
    </nav> <!--End of navbar-->

    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

Blog/blog/templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block page_header %}
<h1>{{blog.text}}</h1>
{% endblock page_header %}

{% block content %}

<p>
    <a href="{% url 'blog:new_blog_post' blog.id %}">Add new post</a>
</p>

<ul>
    {% for blog_post in blog_posts %}
    <!--This is calling the blog_posts list set in the new_blog_post function in views.py-->
    <div class="card mb-3">
        <!--Card header with timestamp and edit link-->
        <h4 class="card-header">
            {{blog_post.date_added|date:'M d, Y H:i'}}
            <small>
                <a href="{% url 'blog:edit_blog_post' blog_post.id %}">Edit post</a>
            </small>
        </h4>
        <!--Card body with entry text-->
        <div class="card-body"> {{blog_post.text|linebreaks}}</div>
    </div>
    {% empty %}
    <p>There are no posts for this blog yet</p>
    {% endfor %}
</ul>

{% endblock content %}

Blog/blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1>All Blogs</h1>
{% endblock page_header %}

{% block content %}

<p>Blog Names</p>
<ul class="list-group border-bottom pb-2 mb-4">
    {% for blog in blogs %}
    <li class="list-group-item border-0">
        <a href="{% url 'blog:blog' blog.id %}">{{blog.text}}</a>
        <!--Here we are looking to the view.py folder for functions to call-->
    </li>
    {%empty%}
    <li class="list-group-item border-0">No blogs have been entered yet.</li>
    {% endfor %}
</ul>

<h4><a href="{% url 'blog:new_blog' %}">Add a new blog</a></h4>

{% endblock content %}

Blog/blog/templates/blog/edit_blog_post.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1><a href="{% url 'blog:blog' blog.id %}">{{blog}}</a></h1>
{% endblock page_header %}

{% block content%}

<ul>
    <h5>Edit blog post:</h5>
    <form action="{% url 'blog:edit_blog_post' blog_post.id %}" method='post'>
        <!--Line 9 sends the form back to the edit_entry function in views.py-->
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Save changes" %}
    </form>
</ul>

{% endblock content%}

Blog/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
        <h1 class="display-3">Track your Blogs</h1>
        <p class="lead">Make your own blog and keep a list of any and all entries along the way.</p>
        <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
    </div>
</div>
{% endblock page_header %}

Blog/blog/templates/blog/new_blog.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1>Create a new Blog</h1>
{% endblock page_header %}

{% block content %}

<p>Blog Title:</p>

<form action="{% url 'blog:new_blog' %}" method='post'>
    <!-- The above line we are telling Django to submit the data included in the form to the view file, and specifically the function, new_topic-->
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="+ Add" %}
</form>

{% endblock content%}

Blog/blog/templates/blog/new_blog_post.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1><a href="{% url 'blog:blog' blog.id %}">{{blog}}</a></h1>
{% endblock page_header %}

{% block content %}

<form action="{% url 'blog:new_blog_post' blog.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="+ Add new post" %}
</form>

{% endblock content %}