Pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Page showing all pizzas.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Page showing an individual pizza.
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
]

Pizzeria/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

Pizzeria/pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """Represent a pizza that can be ordered from the pizzeria."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

class Topping(models.Model):
    """A topping that can be added to a pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

Pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for Pizzeria."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Page showing all pizzas that are available."""
    pizzas = Pizza.objects.all()
    #Okay so for pizzas we just grab... everything. We want every bit of information we can get about pizzas
    #Which includes: name, date_added
    context = {'pizzas': pizzas}
    #We pass the pizza dictionary to the pizzas.html file
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Page showing information about an individual pizza."""
    pizza = Pizza.objects.get(id=pizza_id)
    #We are grabbing the very specific pizza.
    #This id is passed in by the urls.py file
    #Then when the pizzas.html file is run through those individual IDs are found and added to URLs
    toppings = pizza.topping_set.all()
    #This is some Python shenanigans not taught in the book
    #In the book they used entry_set when there is a one to one relationship.
    #Here we have to use _set which I don't fully understand why to be honest
    #https://stackoverflow.com/questions/54714887/object-has-no-attribute-entry-set-error
    #foo_set
    #I have to use the Topping class in lower case to grab this
    #Reference back to Page 387

    #But here you can have multiple toppings assigned to one pizza!

    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

Pizzeria/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

Pizzeria/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
<p>Welcome to the Pizzeria! We hope you'll find a pizza that you like. :)</p>
{% endblock content %}

Pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizza: {{ pizza.name }}</p>

<p>Toppings:</p>
<ul>
    {% for topping in toppings %}
    <li>{{ topping.name }}</li>
    {% empty %}
    <li>There are no toppings on this pizza.</li>
    {% endfor %}
</ul>

{% endblock content %}

Pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}
<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name }}</a>
        <!-- This pizzas:pizza is actually calling the pizza function in the views.py file -->
        <!-- That's why the pizza.id is included as an argument! -->
    </li>
    {% empty %}
    <li>We don't currently have any pizzas available.</li>
    {% endfor %}
</ul>

{% endblock content %}

<!-- Okay so my HTML files should look at my views.py files -->

<!-- <a> href = "{% url 'pizzas:pizza' pizza.id %}"</a>

So we're telling it to look for pizzas dictionary passed in by views.py
We also want it to put into the URL ITSELF AS THE LINK. The ID associated with the first pizza found in the dictionary list
From there we say just spit out the pizza.name

Because the pizzas dictionary we are passing into this from views.html is referencing the models.py file
And in there pizzas can have: name, date_added

-->